name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d

      - name: Sleep
      - uses: jakejarvis/wait-action@master
        with:
          time: '60s'

      - name: Check running containers
        run: docker ps
